[tox]
envlist = py311, py312
skipsdist = false

[testenv]
deps =
    -r requirements.txt
commands =
    pytest wikimon/test_monitor.py wikimon/test_parsers.py wikimon/test_multi_lang_server.py -v {posargs}
