[program:wikimon]
command=/home/hatnote/wikimon-v2/venv/bin/python -m wikimon.monitor --port 9500 --loglevel INFO
directory=/home/hatnote/wikimon-v2
user=hatnote
autostart=true
autorestart=true
stderr_logfile=/home/hatnote/wikimon-v2/logs/wikimon.err.log
stdout_logfile=/home/hatnote/wikimon-v2/logs/wikimon.out.log
