server {
    server_name  wikimon.hatnote.com;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/hatnote.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hatnote.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log  /home/hatnote/wikimon/logs/access.log combined buffer=128k flush=10s;
    error_log   /home/hatnote/wikimon/logs/error.log;

    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "Upgrade";
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_read_timeout 86400s;
    proxy_send_timeout 86400s;

    location /       { proxy_pass http://127.0.0.1:9000; }
    location /en/    { proxy_pass http://127.0.0.1:9000; }
    location /de/    { proxy_pass http://127.0.0.1:9010; }
    location /ru/    { proxy_pass http://127.0.0.1:9020; }
    location /ja/    { proxy_pass http://127.0.0.1:9030; }
    location /es/    { proxy_pass http://127.0.0.1:9040; }
    location /fr/    { proxy_pass http://127.0.0.1:9050; }
    location /nl/    { proxy_pass http://127.0.0.1:9060; }
    location /it/    { proxy_pass http://127.0.0.1:9070; }
    location /sv/    { proxy_pass http://127.0.0.1:9080; }
    location /ar/    { proxy_pass http://127.0.0.1:9090; }
    location /id/    { proxy_pass http://127.0.0.1:9100; }
    location /ta/    { proxy_pass http://127.0.0.1:9110; }
    location /pa/    { proxy_pass http://127.0.0.1:9120; }
    location /mr/    { proxy_pass http://127.0.0.1:9130; }
    location /hi/    { proxy_pass http://127.0.0.1:9140; }
    location /as/    { proxy_pass http://127.0.0.1:9150; }
    location /bn/    { proxy_pass http://127.0.0.1:9160; }
    location /te/    { proxy_pass http://127.0.0.1:9165; }
    location /kn/    { proxy_pass http://127.0.0.1:9170; }
    location /or/    { proxy_pass http://127.0.0.1:9180; }
    location /sa/    { proxy_pass http://127.0.0.1:9190; }
    location /gu/    { proxy_pass http://127.0.0.1:9200; }
    location /fa/    { proxy_pass http://127.0.0.1:9210; }
    location /wikidata/ { proxy_pass http://127.0.0.1:9220; }
    location /he/    { proxy_pass http://127.0.0.1:9230; }
    location /zh/    { proxy_pass http://127.0.0.1:9240; }
    location /ml/    { proxy_pass http://127.0.0.1:9250; }
    location /pl/    { proxy_pass http://127.0.0.1:9260; }
    location /mk/    { proxy_pass http://127.0.0.1:9270; }
    location /be/    { proxy_pass http://127.0.0.1:9280; }
    location /sr/    { proxy_pass http://127.0.0.1:9290; }
    location /bg/    { proxy_pass http://127.0.0.1:9300; }
    location /uk/    { proxy_pass http://127.0.0.1:9310; }
    location /hu/    { proxy_pass http://127.0.0.1:9320; }
    location /fi/    { proxy_pass http://127.0.0.1:9330; }
    location /no/    { proxy_pass http://127.0.0.1:9340; }
    location /el/    { proxy_pass http://127.0.0.1:9350; }
    location /eo/    { proxy_pass http://127.0.0.1:9360; }
    location /pt/    { proxy_pass http://127.0.0.1:9370; }
    location /et/    { proxy_pass http://127.0.0.1:9380; }
    location /ur/    { proxy_pass http://127.0.0.1:9390; }
    location /ro/    { proxy_pass http://127.0.0.1:9400; }
    location /hy/    { proxy_pass http://127.0.0.1:9410; }
}

server {
    server_name  wikimon.hatnote.com;
    listen 80;
    return 301 https://$host$request_uri;
}
